name: Automate pot file creation
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update-pot-file:
    strategy:
      # only one job at once otherwise one job will push and second job will get conflict on remote
      max-parallel: 1
      # update this matrix to support new Anaconda branches
      matrix:
        branch: [ master, f34 ]
        include:
          - branch: master
            anaconda-branch: master
          - branch: f34
            anaconda-branch: f34-devel

    runs-on: ubuntu-latest
    container:
      image: docker://quay.io/rhinstaller/anaconda-ci:${{ matrix.anaconda-branch }}
    steps:
      - name: Checkout anaconda ${{ matrix.anaconda-branch }}
        uses: actions/checkout@v2
        with:
          path: anaconda
          repository: rhinstaller/anaconda
          ref: ${{ matrix.anaconda-branch }}
      - name: Create pot file
        run: |
          echo "Creating pot file..."
          pushd anaconda
          ./autogen.sh
          ./configure
          make
          make pot-update-check
          popd
      - name: Checkout anaconda-l10n
        uses: actions/checkout@v2
        with:
          path: anaconda-l10n
          ref: master
      - name: Push new potfile
        run: |
          cp -v anaconda/po/anaconda.pot anaconda-l10n/${{ matrix.branch }}
          cd anaconda-l10n
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update pot-file"
          git push
